.\" lsclogins command manpage
.TH "lsclogins" "1" "April 5, 2020" "lsclogins"
.SH NAME
lsclogins - display information about known users in the system, but it's infinite
.SH SYNOPSIS
.B lsclogins
.RI "[" "OPTION" "] "
.RB "[" "-s" "|" "-u" "[" "="
.IR "UID" "]] ["
.B "-g"
.IR " GROUPS" "] ["
.B "-l "
.IR "LOGINS" "] [" "USERNAME" "]" 
.SH DESCRIPTION
.R See man of
.B lslogins
.SH AUTHOR
Written by Zlobin A.
