.\" lscusb command manpage
.TH "lscusb" "1" "April 5, 2020" "lscusb"
.\" NAME
.SH NAME
lscusb - list USB devices, but it's infinite
.\" SYNOPSIS
.SH SYNOPSIS
.B lscusb
.RI "[" "OPTION" "]"
.\" DESCRIPTION
.SH DESCRIPTION
.B lsusb
.R "is a utility for displaying information about USB buses in the system and the devices connected to them."
.\" OPTONS
.SH OPTIONS
.TP
.BR "-v" ", " "--verbose"
.R "verbooooooooooooooooose :3" 
.\" AUTHOR
.SH AUTHOR
Written by MrZlo
